### ISSUE TITLE
Heatmap for postive tests per age group is getting pretty crowded

### ISSUE THREAD

**Issue by JonasCir** [dbvis-ukon/coronavis#2]
Hey there,
thanks for creating this useful tool!

Just noticed that if you select a district and take a look at the heatmap, the numbers are barely readable anymore.
Is there a way to add a horizontal scrollbar to it? 

![heatmap](https://user-images.githubusercontent.com/20031875/156403596-bc575c5e-a9d6-4888-bed9-1fc93533ddf8.png)

**Comment by wjentner** [comment]
Hi, the issue should be fixed with this release: https://github.com/dbvis-ukon/coronavis/releases/tag/v1.22.61

**Comment by JonasCir** [comment]
Thanks for the fast reply :+1:
